
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1cyQPxpkQPbQf5WtNcPAXLOdMXq9Fdw',
    authDomain: 'pc-api-5518905543325100771-114.firebaseapp.com',
    projectId: 'pc-api-5518905543325100771-114',
    storageBucket: 'pc-api-5518905543325100771-114.appspot.com',
    messagingSenderId: '158003833341',
    appId: '1:158003833341:web:601cf91915c9202908d194',
    measurementId: 'G-G6L510ZJ7V'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HwDgsSw3mLMKupUpRMAa3UJQRXz1zhg',
    iosBundleId: 'com.example.helloWorld',
    appId: '1:158003833341:ios:62f0b8bdf089288d08d194',
    storageBucket: 'pc-api-5518905543325100771-114.appspot.com',
    messagingSenderId: '158003833341',
    iosClientId: '158003833341-ies53sj6kdk4hduiei0juscstmfc0dv8.apps.googleusercontent.com',
    projectId: 'pc-api-5518905543325100771-114'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23tRhYmY4UlyBvqigpRQnT081GXtdym8',
    appId: '1:158003833341:android:e092530804a86da308d194',
    messagingSenderId: '158003833341',
    projectId: 'pc-api-5518905543325100771-114',
    storageBucket: 'pc-api-5518905543325100771-114.appspot.com'
  );
}
